export const ADD_LOCATION = 'ADD_LOCATION'
export const GET_LOCATIONS = 'GET_LOCATIONS'

export const ADD_TEST_RESULTS = 'ADD_TEST_RESULTS'
export const GET_TEST_RESULTS = 'GET_TEST_RESULTS'
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const CHECK_LOGIN = 'CHECK_LOGIN';

export const ADD_PREFERENCES = 'ADD_PREFERENCES';
export const GET_PREFERENCES = 'GET_PREFERENCES';

export const GET_FRIENDS = 'GET_FRIENDS';
